# Generated by Django 6.1.1 on 2026-09-21 21:36

import trips.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_id', models.CharField(db_index=True, default=trips.models.make_share_id, max_length=16, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('cycle_hours_used', models.FloatField()),
                ('start_time', models.DateTimeField()),
                ('avg_speed_mph', models.FloatField(default=55.0)),
                ('cycle_limit_hours', models.PositiveSmallIntegerField(default=70)),
                ('include_inspections', models.BooleanField(default=False)),
                ('payload', models.JSONField()),
                ('total_miles', models.FloatField(default=0)),
                ('driving_hours', models.FloatField(default=0)),
                ('log_day_count', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['-created_at'], name='trips_trip_created_44654c_idx')],
            },
        ),
    ]
